function Export-DriftHTML {
    [CmdletBinding()]
    [OutputType([string])]
    param(
        [Parameter(Mandatory)] [AllowEmptyCollection()] [object[]]$Findings = @(),
        [Parameter(Mandatory)] [string]$TenantId,
        [Parameter(Mandatory)] [string]$OutputPath,
        [string]$BaselineVersion = "unknown"
    )

    $Findings = @($Findings)
    $dir = Split-Path $OutputPath -Parent
    if ($dir -and -not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }

    $generated = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss zzz")

    $critical = @($Findings | Where-Object { $_.Severity -eq "Critical" }).Count
    $high     = @($Findings | Where-Object { $_.Severity -eq "High" }).Count
    $medium   = @($Findings | Where-Object { $_.Severity -eq "Medium" }).Count
    $low      = @($Findings | Where-Object { $_.Severity -eq "Low" }).Count
    $total    = $Findings.Count

    $sevColor = @{
        Critical = "#DC2626"
        High     = "#EA580C"
        Medium   = "#CA8A04"
        Low      = "#16A34A"
        Info     = "#2563EB"
    }

    $rows = foreach ($f in ($Findings | Sort-Object Severity, FindingId)) {
        $c = if ($sevColor[$f.Severity]) { $sevColor[$f.Severity] } else { "#64748B" }
        $exp = if ($null -eq $f.ExpectedValue) { "<em>absent</em>" } else { "$($f.ExpectedValue)" -replace "<","&lt;" -replace ">","&gt;" }
        $obs = if ($null -eq $f.ObservedValue) { "<em>absent</em>" } else { "$($f.ObservedValue)" -replace "<","&lt;" -replace ">","&gt;" }
        $rn  = if ($f.ResourceName) { $f.ResourceName } else { "—" }
        "<tr><td><code>$($f.FindingId)</code></td><td><span class=""sev"" style=""background:$c"">$($f.Severity)</span></td><td>$($f.Category)</td><td>$rn</td><td><code>$($f.ChangedProperty)</code></td><td>$exp</td><td>$obs</td></tr>"
    }
    $rows = $rows -join "`n"

    $html = @"
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Entra Configuration Drift Report</title>
<style>
  * { box-sizing: border-box; }
  body { font-family: -apple-system, Segoe UI, Roboto, sans-serif; margin: 0; padding: 0; background: #F1F5F9; color: #0F172A; }
  .container { max-width: 1400px; margin: 0 auto; padding: 32px; }
  h1 { font-size: 26px; margin: 0 0 8px 0; }
  h2 { font-size: 18px; margin: 32px 0 12px 0; border-bottom: 2px solid #E2E8F0; padding-bottom: 6px; }
  .meta { color: #64748B; font-size: 13px; margin-bottom: 24px; }
  .metrics { display: flex; gap: 16px; margin: 24px 0; }
  .metric { flex: 1; background: white; border-radius: 8px; padding: 20px; text-align: center; box-shadow: 0 1px 3px rgba(0,0,0,0.08); }
  .metric .val { font-size: 32px; font-weight: 700; }
  .metric .lbl { font-size: 11px; color: #64748B; text-transform: uppercase; letter-spacing: 0.05em; margin-top: 4px; }
  table { width: 100%; border-collapse: collapse; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.08); }
  th { text-align: left; padding: 10px 14px; background: #F8FAFC; font-size: 11px; text-transform: uppercase; color: #64748B; border-bottom: 1px solid #E2E8F0; }
  td { padding: 10px 14px; border-bottom: 1px solid #F1F5F9; font-size: 13px; vertical-align: top; }
  td code { background: #F1F5F9; padding: 2px 6px; border-radius: 4px; font-size: 11px; }
  .sev { display: inline-block; padding: 2px 8px; border-radius: 999px; color: white; font-weight: 600; font-size: 10px; text-transform: uppercase; letter-spacing: 0.03em; }
  footer { text-align: center; color: #94A3B8; font-size: 11px; margin-top: 40px; }
</style>
</head>
<body>
<div class="container">
  <h1>Entra ID Configuration Drift Report</h1>
  <div class="meta">Tenant: <code>$TenantId</code> · Generated: $generated · Baseline: <code>$BaselineVersion</code></div>

  <div class="metrics">
    <div class="metric"><div class="val" style="color:#DC2626">$critical</div><div class="lbl">Critical</div></div>
    <div class="metric"><div class="val" style="color:#EA580C">$high</div><div class="lbl">High</div></div>
    <div class="metric"><div class="val" style="color:#CA8A04">$medium</div><div class="lbl">Medium</div></div>
    <div class="metric"><div class="val" style="color:#16A34A">$low</div><div class="lbl">Low</div></div>
    <div class="metric"><div class="val">$total</div><div class="lbl">Total Findings</div></div>
  </div>

  <h2>Drift Findings ($total)</h2>
  <table>
    <thead><tr><th>Finding</th><th>Severity</th><th>Category</th><th>Resource</th><th>Property</th><th>Expected</th><th>Observed</th></tr></thead>
    <tbody>
$rows
    </tbody>
  </table>

  <footer>Generated by Entra-ID-Configuration-Drift-Engine v0.6.0</footer>
</div>
</body>
</html>
"@

    $html | Set-Content -Path $OutputPath -Encoding UTF8
    Write-DriftLog -Message ("HTML written: {0}" -f $OutputPath) -Level Success -Component "Report"
    return $OutputPath
}
